### ISSUE TITLE
Do you use the whole training set of Imagenet?  And could you share the parameters for imdep?

### ISSUE THREAD

**Issue by theFool32** [OmidPoursaeed/Generative_Adversarial_Perturbations#3]
Hi, thanks for your job and willing to share codes.
I am working on similar project about imdep. However, you only give the example to train a universal one. Could you please share the parameters for imdep (e.g. batchSize, nEpochs)?

Thanks a lot.

**Comment by OmidPoursaeed** [comment]
Hi. We use mostly similar values as those for universal. 
You don't need to use the whole training set. Using a small subset of Imagenet suffice, and the model converges pretty fast.

**Comment by theFool32** [comment]
Thanks for your response.  :)
