### ISSUE TITLE
Segmentation attack - GPU resources with Unet generator

### ISSUE THREAD

**Issue by MichaKh** [OmidPoursaeed/Generative_Adversarial_Perturbations#6]
Hi,

I am trying to run your implementation for the adversarial attack on the pre-trained "fcn8s-atonce" segmentation model:
1. According to the `GAP_seg.py` script arguments, the `--gpu_ids` flag can be set to -1 (to run it on CPU). Is the code compatible with CPU run?
2. When trying to run the code on 2 GPUs, I am encountering "CUDA memory" issues. What is the configuration that you used for the implementation? What Pytorch/torchvision/CUDA versions, with how much CUDA memory?

Thanks

**Comment by OmidPoursaeed** [comment]
Hi,

I am not sure if the semantic segmentation code is compatible with CPU and can be run on multiple GPUs. We checked these with classification though, and they work.

Thanks
